In [2]:
import numpy as np

#### numpy배열의 모양

In [4]:
A = np.array([[1,1,1], [2,3,4]])
A

array([[1, 1, 1],
       [2, 3, 4]])

In [5]:
A.shape

(2, 3)

In [6]:
B = np.array([
    [[1,2,3], [1,2,3]],
    [[2,3,4], [5,6,7]]
])

In [7]:
B.shape

(2, 2, 3)

#### numpy one, zero 배열 생성

In [9]:
import numpy as np

In [10]:
# 2 x 3의 모양을 가지고 1로 채워진 배열을 만들어줍니다.
ones_arr = np.ones(shape=(2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# 2 x 3의 모양을 가지고 0으로 채워진 배열을 만들어줍니다.
zeros_arr = np.zeros(shape=(2, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

#### numpy 랜덤 배열 생성

In [13]:
import numpy as np

In [14]:
# 3 x 2의 모양을 가진 배열을 랜덤하게 만들어줍니다.
rand_arr = np.random.normal(size=(3,2))
rand_arr

array([[-2.35120681,  0.2118284 ],
       [-0.41560054, -1.99963718],
       [ 1.32642213, -0.73679751]])

In [15]:
# 3 x 2의 모양을 가진 배열을 정규 분포에 따라 랜덤하게 만들어줍니다.
# loc : 평균(mean)
# scale : 표준편차(std)
rand_normal_arr = np.random.normal(loc =3, scale=0.25, size=(3,2))
rand_normal_arr

array([[3.32601036, 3.13510712],
       [3.20552321, 3.26385348],
       [2.69093957, 2.96880133]])

In [17]:
# 3 x 2의 모양을 가지고, 1부터 9까지 임의의 정수로만 이루어진 배열을 만들어줍니다.
# randint(start, end, size)
rand_int_arr = np.random.randint(1, 10, size=(3,2))
rand_int_arr

array([[7, 9],
       [4, 5],
       [6, 7]])

In [18]:
# 파이썬의 random패키지와 같이 seed를 고정하여 일정하게 랜덤값을 유지할 수 있습니다.

In [21]:
np.random.seed(42)
print(np.random.randn(3, 2))
np.random.seed(42)
print(np.random.randn(3, 2))

[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]
[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]


In [22]:
#### Numpy 특정 요소 읽어오기

In [23]:
import numpy as np
arr = [1, 3, 10, 55, 31, 12, 15]
A = np.array(arr)
A[3]

55

In [24]:
import numpy as np
arr = [[1,2,4], [12, 15, 17]]
print(arr[1][2])

17


In [25]:
np_arr = np.array(arr)
np_arr[1][2]

17

In [26]:
np_arr[1, 2]

17

#### numpy 특정 요소 변경하기


In [28]:
import numpy as np
arr = [1, 3, 10, 55, 31, 12, 15]
A = np.array(arr)
A[3] = 22
A

array([ 1,  3, 10, 22, 31, 12, 15])

In [29]:
import numpy as np
arr = [[1,2,4], [12, 15, 17]]
np_arr = np.array(arr)
np_arr[1,2] = 100
np_arr

array([[  1,   2,   4],
       [ 12,  15, 100]])

In [30]:
#### numpy 덧셈

In [31]:
li_A = [1, 2, 3, 4, 5]
li_B = [6, 7, 8, 9, 10]
result = [a + b for a, b in zip(li_A, li_B)]
result

[7, 9, 11, 13, 15]

In [32]:
import numpy as np
arr_A = np.array([1, 2, 3, 4, 5])
arr_B = np.array([6, 7, 8, 9, 10])
result = arr_A + arr_B
result

array([ 7,  9, 11, 13, 15])

#### 브로드캐스팅

In [33]:
A = [
    [10, 10, 10, 10, 10],
    [20, 20, 20, 20, 20],
    [30, 30, 30, 30, 30],
    [40, 40, 40, 40, 40],
    [50, 50, 50, 50, 50]
]
A = np.array(A)
A

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50]])

In [34]:
B = np.array([[13] * 5 for _ in range(5)])
B

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [35]:
C = np.array([[13, 13, 13], [13, 13, 13]])
C

array([[13, 13, 13],
       [13, 13, 13]])

In [37]:
result = A + B
result

array([[23, 23, 23, 23, 23],
       [33, 33, 33, 33, 33],
       [43, 43, 43, 43, 43],
       [53, 53, 53, 53, 53],
       [63, 63, 63, 63, 63]])

In [38]:
result = A + C

ValueError: operands could not be broadcast together with shapes (5,5) (2,3) 

In [39]:
A = [
    [10, 10, 10, 20, 20],
    [21, 87, 31, 25, 64],
    [16, 39, 10, 23, 30],
    [88, 13, 52, 12, 47],
    [53, 23, 41, 16, 73]
]


In [40]:
A

[[10, 10, 10, 20, 20],
 [21, 87, 31, 25, 64],
 [16, 39, 10, 23, 30],
 [88, 13, 52, 12, 47],
 [53, 23, 41, 16, 73]]

In [42]:
A = np.array(A)
A

array([[10, 10, 10, 20, 20],
       [21, 87, 31, 25, 64],
       [16, 39, 10, 23, 30],
       [88, 13, 52, 12, 47],
       [53, 23, 41, 16, 73]])

In [43]:
result1 = A + 13
result1

array([[ 23,  23,  23,  33,  33],
       [ 34, 100,  44,  38,  77],
       [ 29,  52,  23,  36,  43],
       [101,  26,  65,  25,  60],
       [ 66,  36,  54,  29,  86]])

In [44]:
B = np.array([1, 2, 3, 4, 5])
result2 = A + B
result2

array([[11, 12, 13, 24, 25],
       [22, 89, 34, 29, 69],
       [17, 41, 13, 27, 35],
       [89, 15, 55, 16, 52],
       [54, 25, 44, 20, 78]])

#### Numpy dot 메소드

In [46]:
import numpy as np

In [47]:
A = np.array([[1, 2], [2, 3]])
B = np.array([[4, 1], [6, 7]])
A * B

array([[ 4,  2],
       [12, 21]])

In [48]:
A.dot(B)

array([[16, 15],
       [26, 23]])

In [49]:
np.dot(A, B)

array([[16, 15],
       [26, 23]])

#### numpy 1차원 배열 슬라이싱1

In [51]:
li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
li[3:7]

[4, 5, 6, 7]

In [52]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[3:7]

array([4, 5, 6, 7])

In [53]:
import numpy as np
arr = [i * j for j in range(10) for i in range(10)]
arr = np.array(arr)
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  3,  6,  9,
       12, 15, 18, 21, 24, 27,  0,  4,  8, 12, 16, 20, 24, 28, 32, 36,  0,
        5, 10, 15, 20, 25, 30, 35, 40, 45,  0,  6, 12, 18, 24, 30, 36, 42,
       48, 54,  0,  7, 14, 21, 28, 35, 42, 49, 56, 63,  0,  8, 16, 24, 32,
       40, 48, 56, 64, 72,  0,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [54]:
arr.shape

(100,)

In [57]:
# arr의 42번 인덱스부터 56번 인덱스까지 슬라이싱을 해주세요.
result = arr[42: 57]
result

array([ 8, 12, 16, 20, 24, 28, 32, 36,  0,  5, 10, 15, 20, 25, 30])

#### numpy 1차원 배열 슬라이싱 2

In [59]:
li = [1, 2, 3, 4, 5, 6, 7]
li[2:4] = [4, 3]
li

[1, 2, 4, 3, 5, 6, 7]

In [60]:
li[2:4] = [10, 20, 30, 40]
li

[1, 2, 10, 20, 30, 40, 5, 6, 7]

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[3:7]

array([4, 5, 6, 7])

In [62]:
arr[3:7] = np.array([100, 45, 60, 75])
arr

array([  1,   2,   3, 100,  45,  60,  75,   8,   9,  10])

In [65]:
# list의 리스트와 달리 numpy.ndarray의 배열을 슬라이싱하여 값을 변경할 때, 크기 또는 모양이 맞지 않으면 에러를 발생합니다. 즉, 슬라이싱을 이용하여 값을 변경할 때는 대입할 배열의 모양이 슬라이싱을 한 구간과 일치해야 합니다.
arr[3:7] = np.array([1, 1, 1, 1, 1])

ValueError: could not broadcast input array from shape (5) into shape (4)

In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[3:7] = 100
arr

array([  1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [71]:
import numpy as np

arr = [i * j for j in range(10) for i in range(10)]
arr = np.array(arr)


In [73]:
arr[35: 50] = 1

#### numpy 2차원 배열 슬라이싱1


In [75]:
li = [
    [1, 2, 3, 4, 5],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9],
    [10, 11, 14, 15, 17]
]

In [76]:
li[1:3][2:4]

[]

In [77]:
li = [
    [1, 2, 3, 4, 5],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9],
    [10, 11, 14, 15, 17]
]

li2 = []
for i in range(1, 3):
    li2.append(li[i][2:4])

In [78]:
li2

[[6, 7], [7, 8]]

In [80]:
[x[2:4] for x in li[1:3]]

[[6, 7], [7, 8]]

#### 2차원 배열 슬라이싱

In [83]:
import numpy as np

arr = np.array(
[
    [1, 2, 3, 4, 5],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 9, 9],
    [10, 11, 14, 15, 17]
]
)

arr[1:3, 2:4]

array([[6, 7],
       [7, 9]])

#### 2차원 배열 슬라이싱 2

In [345]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9],
    [10, 11, 14, 15, 17]
])


In [346]:
arr[1:3, 1:3] = np.array([[10, 20], [30, 40]])

In [347]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 4, 10, 20,  7,  8],
       [ 5, 30, 40,  8,  9],
       [10, 11, 14, 15, 17]])

#### 2차원 배열 슬라이싱 연습 1

In [331]:
arr = np.array(
[
    [1, 5, 3, 4, 5, 5, 4, 2, 10, 9],
    [7, 3, 2, 5, 2, 7, 8, 2, 5, 3],
    [3, 2, 5, 6, 7, 8, 2, 10, 6, 5],
    [4, 7, 6, 6, 5, 5, 6, 7, 1, 2]
]
)

In [332]:
y1, x1, y2, x2

NameError: name 'y1' is not defined

In [350]:
import numpy as np

## arr[x1:x2, y1:y2]
def solution(arr, y1, x1, y2, x2):
    answer = np.array(arr)
    answer[y1:y2+1, x1:x2+1] = answer[y1:y2+1, x1:x2+1] * 2

    return answer

In [351]:
solution(arr, 0, 1, 2, 4)

array([[ 1,  4,  6,  8, 10],
       [ 4, 20, 40, 14, 16],
       [ 5, 60, 80, 16, 18],
       [10, 11, 14, 15, 17]])

In [352]:
arr = np.array(
[
    [6, 3, 7, 4, 6],
    [9, 2, 6, 7, 4],
    [3, 7, 7, 2, 5],
    [4, 1, 7, 5, 1],
    [4, 0, 9, 5, 8],
    [0, 9, 2, 6, 3],
    [8, 2, 4, 2, 6]
]
)

In [353]:
solution(arr, 1, 1, 2, 2)

array([[ 6,  3,  7,  4,  6],
       [ 9,  4, 12,  7,  4],
       [ 3, 14, 14,  2,  5],
       [ 4,  1,  7,  5,  1],
       [ 4,  0,  9,  5,  8],
       [ 0,  9,  2,  6,  3],
       [ 8,  2,  4,  2,  6]])

#### 기초문제2 : 내적연산

## y = w^T + b

In [230]:
import numpy as np

def solution(x, w, b):
    answer = 0
    answer = np.dot(x,w) + b
    return answer


In [231]:
x = [1, 2, 3]
w = [3, 4, 5]
b = 7
result = 33

In [232]:
solution(x, w, b)

33

In [233]:
np.transpose(w)

array([3, 4, 5])

In [234]:
np.array(w)

array([3, 4, 5])

#### 기초문제3 : 롤러코스터

In [316]:
import numpy as np

def solution(info):
    answer = []
    #print(info[0])
    for kee in range(0, len(info[0])):
        if info[0][kee] < 150:
            #print(info[0][kee])
            answer.append(kee)
        if info[0][kee] > 195:
            #print(info[0][kee])
            answer.append(kee)
            
    for w in range(0, len(info[1])):
        if info[1][w] > 140:
            #print(info[1][w])
            answer.append(w)
    answer = sorted(answer)
    return answer

In [317]:
info = [[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]]
result = [1,2, 4]

In [318]:
solution(info)

[1, 2, 4]

In [271]:
import numpy as np

def solution(info):
    answer = []
    print(info[0])
    for kee in info[0]:
        if kee < 150:
            print(kee)
        if kee > 195:
            print(kee)
    return answer

In [272]:
info = [[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]]
result = [1,2, 4]

In [273]:
solution(info)

[151.4, 172.45, 138.65, 177.63, 207.46]
138.65
207.46


[]

In [354]:
## np.where 문제인듯


In [402]:
import numpy as np

def solution(info):
    answer = []
    #print(info[0])
    #a = info[0]
    #b = info[1]
    answer.append(np.where(info[0] < np.float64(150))[0][0])
    answer.append(np.where(info[0] > np.float64(195))[0][0])
    answer.append(np.where(info[1] > np.float64(140))[0][0])
    
    answer = sorted(answer)
    return answer

In [403]:
info = [[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]]
result = [1,2, 4]

In [404]:
solution(info)

[1, 2, 4]

In [538]:
import numpy as np

def solution(info):
    answer = []
    #print(info[0])
    #a = info[0]
    #b = info[1]
    #print(np.where(info[0] < np.float64(150))[0][0])
    try:
        set_answer = set([np.where(info[0] < np.float64(150))[0][0]])
    except IndexError:
        print()
    #print(set_answer)
    #print(np.where(info[0] > np.float64(195))[0][0])
    try:
        set_answer.add(np.where(info[0] > np.float64(195))[0][0])
    except IndexError:
        print()

    #print(np.where(info[1] > np.float64(140))[0][0])
    try:
        set_answer.add(np.where(info[1] > np.float64(140))[0][0])
    except IndexError:
        print()
    
    answer = sorted(list(set_answer))
    return answer

In [539]:
info = [[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]]
result = [1,2, 4]

In [540]:
solution(info)

[1, 2, 4]

In [541]:
info = [[196.12, 143.03], [66.23, 43.86]]
result = [1,2, 4]

In [542]:
solution(info)

[0, 1]

In [615]:
import numpy as np

def solution(info):
    answer = []
    #print(info[0] < np.float64(150))
    #print(info[0] > np.float64(195))
    set_answer = {}
    #answer2 = np.where(info[0] < np.float64(150))
    if (info[0] < np.float64(150)) != [False, False]:
        set_answer = set([np.where(info[0] < np.float64(150))[0][0]])
    print(set_answer)
    if (info[0] > np.float64(195)) != [False, False]:
        set_answer.add(np.where(info[0] > np.float64(195))[0][0])
    print(set_answer)
    print(info[1] > np.float64(140))
    if (info[1] > np.float64(140)) != [False, False]:
        set_answer.add(np.where(info[1] > np.float64(140))[0][0])
    print(set_answer)
    
    #np.where(info[0] > np.float64(195))
    #set_answer = set([[0][0]])
    #answer2 = np.where(info[1] > np.float64(140))
    #if answer2 != []:
    #    set_answer.add(answer2)
    return answer
    

In [616]:
info = [[196.12, 143.03], [66.23, 43.86]]
result = [1,2, 4]

In [617]:
solution(info)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [662]:
import numpy as np

def solution(info):
    answer = []
    
    set_answer = set()
    
    for k in range(0, len(info)):
        #rint(k)
        #print(info[k])
        for w in range(0, len(info[k])):
            ## 키
            if k == 0:
                if info[k][w] < np.float64(150):
                    #print(w)
                    set_answer.add(w)
                elif info[k][w] > np.float64(195):
                    #print(w)
                    set_answer.add(w)
            ## 몸무게
            elif k == 1:
                if info[k][w] > np.float64(140):
                    #print(w)
                    set_answer.add(w)
                #print(info[k][w])
    
    
    answer = sorted(list(set_answer))
    return answer

In [663]:
info = [[151.4, 172.45, 138.65, 177.63, 207.46], [ 44.64, 163.5, 112.35, 73.55, 97.83]]
result = [1,2, 4]

In [664]:
solution(info)

[1, 2, 4]

#### 기초문제4 : 행렬 곱 실습문제

#### 초기 A의 상태는 [[0]] 입니다.
#### arr_list, A와 arr를 행렬 곱 연산이 불가할 때, arr을 버리고 다음 배열을 꺼냅니다.
#### arr_list, A와 arr를 행렬 곱 연산이 불가할 때, 다음과 같이 연산하고 다음 배열을 꺼냅니다.
#### A = (A + 1) * (arr * 2)


In [481]:
arr_list = [[[ -9, -14]], [[ 14, -2, 0], [-14, -5, 1], [-11, 3, -6]], [[-2, -6], [18, 0]]]
result = [[-904., 204.]]

In [ ]:
import numpy as np

def solution(arr_list):
    answer1 = np.array([[0]])
    
    for item in arr_list:
        try:
            answer1 = answer1 + np.array([[1]])
            #print('answer1 : ', answer1)
            answer2 = item * np.array([[2]])
            #print('answer2 : ', answer2)
            answer1 = np.dot(answer1, answer2)
            #print('result >>> ', answer1)
        except ValueError:
            answer1 = answer1 - np.array([[1]])
            #print('ValueError >>> ')
            continue
        #print(answer1)
    #print(answer)
    return answer1

In [683]:
import numpy as np

def solution(arr_list):
    answer1 = np.array([[0]])
    
    for item in arr_list:
        #print('item > : ', item)
        
        answer1 = answer1 + np.array([[1]])
        #print('answer1.shape : ', answer1.shape[1])
        #print('answer1 : ', answer1)
        answer2 = item * np.array([[2]])
        #print('answer2.shape : ', answer2.shape[0])
        #print('answer2 : ', answer2)
        if answer1.shape[1] != answer2.shape[0]:
            answer1 = answer1 - np.array([[1]])
            continue
        else:
            answer1 = np.dot(answer1, answer2)
                
    #print(answer)
    return answer1

In [684]:
solution(arr_list)

array([[-904,  204]])

In [669]:
answer1 = np.array([[0]])
answer1 = answer1 + 1
answer1 

array([[1]])

In [432]:
answer2 = np.array([[ -9, -14]])
answer2 = answer2 * 2
answer2 

array([[-18, -28]])

In [433]:
np.dot(answer1, answer2)

array([[-18, -28]])

#### 이미지 변환

#### bool 인덱싱

In [686]:
import numpy as np

A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
print(A >= 4)

[False False False  True  True  True False False False]


In [687]:
np.where(A >= 4)

(array([3, 4, 5]),)

In [688]:
A[np.where(A >= 4)]

array([4, 5, 4])

In [691]:
B = ( A >= 4)
A[B]

array([4, 5, 4])

In [695]:
A[(A > 1) & (A <= 3)] = 0
print((A > 1) & (A <= 3))
A

[False False False False False False False False False]


array([1, 0, 0, 4, 5, 4, 0, 0, 1])

In [712]:
import numpy as np

np.random.seed(42)

arr = np.random.randint(0, 100, size=(5, 6, 3))

# arr에서 10보다 크고 20보다 작거나 같은 요소들만 추출해봅시다.
#print(arr)
#print(arr > 10)
#print(arr <= 20)
#print(np.logical_and(arr > 10, arr <= 20))
print(arr[np.logical_and(arr > 10, arr <= 20)])

#print(result)

[14 20 20 14 20 17 13 17 13 14]


#### numpy 관계 연산

In [714]:
'''
Numpy 관계 연산
문제 설명
목표
Numpy의 특별한 관계 연산을 배워봅시다.

Numpy의 특별한 관계 연산
파이썬 객체 사이에 >, <, ==등 관계 연산자들을 사용하면 연산 결과로 True, False가 나옵니다. 그러나 numpy.ndarray타입의 배열에 관계 연산자를 사용하면 관계 연산의 결과가 하나의 bool타입의 값이 아닌 배열로 나옵니다.
numpy.ndarray 배열에 관계 연산자를 사용하면 어떻게 출력하는지 살펴봅시다.

>>> import numpy as np

>>> A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
>>> B = (A >= 4)
>>> print(B)
[False False False  True  True  True False False False]
A에 관계 연산자 >=를 사용하여 연산한 결과를 B에 넣어주었습니다. 그리고 출력한 결과, A에서 4 이상의 값을 가진 요소는 True, 4 미만의 값을 가진 요소는 False를 가지는 배열 B가 생성된 것을 알 수 있습니다.
즉, 배열에 관계 연산자를 사용하면 배열에서 조건을 만족하는 요소는 True, 만족하지 않다면 False인 numpy.ndarray 타입의 배열로 연산 결과가 나옵니다.

2개 이상의 조건식
Numpy에서 논리 연산자를 사용하여 여러 조건식을 결합할 때, and 및 or가 아닌 & 및 |를 사용합니다. 2개의 조건식을 사용한 다음 코드를 살펴봅시다.

>>> import numpy as np

>>> A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
>>> print((A > 1) & (A <= 3))
[False  True  True False False False  True  True False]
>>> print((A > 3) | (A < 2))
[ True False False  True  True  True False False  True]
첫 번째 print에서 1 초과 및 3 이하의 수를 가진 요소는 True, 1 이하 또는 3 초과의 수를 가진 요소는 False인 배열을 출력합니다.
두 번째 print에서 3 초과 또는 2 미만의 수를 가진 요소는 True, 3 이하 및 2 이상의 수를 가진 요소는 False인 배열을 출력합니다.
그럼 오른쪽 코드의 주석을 참고하여 빈칸을 채운 후 Numpy의 관계 연산을 연습해봅시다.

TIP
여러 개의 조건식을 작성할 때 and와 or로 넣어주면 에러가 발생합니다.

>>> import numpy as np

>>> A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
>>> print((A > 1) and (A <= 3))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
and는 Python의 예약어입니다. and의 피연산자에는 numpy.ndarray가 아닌 bool 타입의 값이 와야 됩니다. 그러나 위 코드에서는 numpy.ndarray 타입의 값이 and의 피연산자입니다. 따라서 Numpy에서는 위와 같이 any() 또는 all()메소드를 사용하여 bool 값으로 변경하라고 에러가 발생한 것입니다(any(), all() 메소드는 [Numpy 심화] - any, all를 참고하세요). 즉, 배열에 관한 여러 조건식을 결합할 때는 and, or가 아닌 &, |를 사용해야 합니다.
'''

'\nNumpy 관계 연산\n문제 설명\n목표\nNumpy의 특별한 관계 연산을 배워봅시다.\n\nNumpy의 특별한 관계 연산\n파이썬 객체 사이에 >, <, ==등 관계 연산자들을 사용하면 연산 결과로 True, False가 나옵니다. 그러나 numpy.ndarray타입의 배열에 관계 연산자를 사용하면 관계 연산의 결과가 하나의 bool타입의 값이 아닌 배열로 나옵니다.\nnumpy.ndarray 배열에 관계 연산자를 사용하면 어떻게 출력하는지 살펴봅시다.\n\n>>> import numpy as np\n\n>>> A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])\n>>> B = (A >= 4)\n>>> print(B)\n[False False False  True  True  True False False False]\nA에 관계 연산자 >=를 사용하여 연산한 결과를 B에 넣어주었습니다. 그리고 출력한 결과, A에서 4 이상의 값을 가진 요소는 True, 4 미만의 값을 가진 요소는 False를 가지는 배열 B가 생성된 것을 알 수 있습니다.\n즉, 배열에 관계 연산자를 사용하면 배열에서 조건을 만족하는 요소는 True, 만족하지 않다면 False인 numpy.ndarray 타입의 배열로 연산 결과가 나옵니다.\n\n2개 이상의 조건식\nNumpy에서 논리 연산자를 사용하여 여러 조건식을 결합할 때, and 및 or가 아닌 & 및 |를 사용합니다. 2개의 조건식을 사용한 다음 코드를 살펴봅시다.\n\n>>> import numpy as np\n\n>>> A = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])\n>>> print((A > 1) & (A <= 3))\n[False  True  True False False False  True  True False]\n>>> print((A > 3) | (A < 2))\n[ True False False  True  True  True False False  Tru

#### Numpy 배열 만들기

In [716]:
import numpy as np

arr = [1, 2, 3, 4, 5]
print(arr, type(arr))

[1, 2, 3, 4, 5] <class 'list'>


In [717]:
np_arr = np.array(arr)
print(np_arr, type(np_arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [719]:
import numpy as np

A = [1, 2, 3, 4, 5]
# A를 np.array()를 이용하여 numpy.ndarray 타입의 배열로 만들어 봅시다.

np_A = np.array(A)
print(np_A)
print(type(np_A))

[1 2 3 4 5]
<class 'numpy.ndarray'>
